// Seed list of high-yield SAT vocab. Used on first launch.
export const SAT_VOCAB_SEED: { word: string; definition: string; example?: string }[] = [
  { word: "Aberration", definition: "A departure from what is normal or expected.", example: "The sudden cold snap was an aberration in July." },
  { word: "Brevity", definition: "Concise and exact use of words.", example: "She spoke with brevity, never wasting a syllable." },
  { word: "Candid", definition: "Truthful and straightforward; frank.", example: "He gave a candid answer to the difficult question." },
  { word: "Diligent", definition: "Showing care and conscientiousness in one's work." },
  { word: "Eloquent", definition: "Fluent or persuasive in speaking or writing." },
  { word: "Frugal", definition: "Sparing or economical with regard to money or food." },
  { word: "Gregarious", definition: "Fond of company; sociable." },
  { word: "Hubris", definition: "Excessive pride or self-confidence." },
  { word: "Indignant", definition: "Feeling or showing anger at unfair treatment." },
  { word: "Juxtapose", definition: "Place close together for contrasting effect." },
  { word: "Laconic", definition: "Using very few words." },
  { word: "Meticulous", definition: "Showing great attention to detail; very careful." },
  { word: "Nefarious", definition: "Wicked or criminal." },
  { word: "Ostentatious", definition: "Designed to impress; pretentiously showy." },
  { word: "Pragmatic", definition: "Dealing with things sensibly and realistically." },
  { word: "Quixotic", definition: "Exceedingly idealistic; unrealistic and impractical." },
  { word: "Rebuke", definition: "Express sharp disapproval or criticism." },
  { word: "Sycophant", definition: "A person who acts obsequiously toward someone for personal gain." },
  { word: "Tenacious", definition: "Tending to keep a firm hold; persistent." },
  { word: "Ubiquitous", definition: "Present, appearing, or found everywhere." },
  { word: "Vehement", definition: "Showing strong feeling; forceful and passionate." },
  { word: "Wary", definition: "Feeling or showing caution about possible dangers." },
  { word: "Xenophobia", definition: "Dislike of or prejudice against people from other countries." },
  { word: "Zealous", definition: "Having or showing great energy or enthusiasm in pursuit of a cause." },
];
